### PR TITLE
[Tools] Deprecate convert tools in tools dir.

### PR DESCRIPTION
**Pull request by Duyi-Wang**
It's better to use pip install xfastertransformer and then `xft.LlamaConvert().convert`  install of git clone and using scripts.

### CODE REVIEW

**Comment by changqi1** [comment]
@abenmao  Please check baichuan and yarn_llama
@a3213105 Please check chatglm and chatglm2
@pujiang2018  Please check llama and opt
@changqi1 Please check qwen

**Review by a3213105 — APPROVED** [review]
has checked chatglm2/3 converter. it works fine in src/xft/tool

**Review by abenmao — APPROVED** [review]
Checked baichuan & llama

**Comment by changqi1** [comment]
Checked qwen

**Review by changqi1 — APPROVED** [review]

**Pull request merged**
