### PR TITLE
[Version] v1.1.0.

### PR DESCRIPTION
**Pull request by Duyi-Wang**
v1.1.0 - Baichuan models supported.

# Models
- Introduced Baichuan models support and added the convert tool for Baichuan models.

# Performance Optimizations
- Update xDNN to version 1.2.1 to improve performance of BF16 data type with AMX instruction on 4th generation Intel Xeon Scalable processors.
- Improved performance of BF16 data type inference by adding matMul bf16bf16bf16 primitives and optimizing kernel selection strategy.
- Improved performance of the model with unbalanced split allocation.

# Functionality
- Auto-detect oneCCL environment and enter single-rank model if oneCCL does not exist.
- Add sample strategy for token search, support temperature, top k, and top P parameter.
- Introduced grouped-query attention support for Llama2.
- Remove mklml 3rd party dependency.
- Add C++ exit function for multi-rank model. 
- Export normalization and position embedding C++ API, including alibi embedding and rotary embedding.
- Introduced `XFT_DEBUG_DIR` environment value to specify the debug file directory.

# BUG fix
- Fix runtime issue of oneCCL shared memory model.
- Fix path concat issue in convert tools.

### CODE REVIEW

**Comment by changqi1** [comment]
@Duyi-Wang  Please create VERSION file to track release info.

**Review by pujiang2018 — APPROVED** [review]

**Comment by Duyi-Wang** [comment]
> @Duyi-Wang Please create VERSION file to track release info.

you mean a version file just containing a version number? or containing the changelog?

**Comment by changqi1** [comment]
> > @Duyi-Wang Please create VERSION file to track release info.
> 
> you mean a version file just containing a version number? or containing the changelog?

Yes. includes version number and containing the changelog.

**Comment by Duyi-Wang** [comment]
> > > @Duyi-Wang Please create VERSION file to track release info.
> > 
> > 
> > you mean a version file just containing a version number? or containing the changelog?
> 
> Yes. includes version number and the changelog.

I will create a version file including the version number. Is changelog necessary? It is included on release page. The PyTorch project use a version file with num https://github.com/pytorch/pytorch/blob/main/version.txt

**Comment by changqi1** [comment]
Need to rebase the base commit.

**Comment by Duyi-Wang** [comment]
> Need to rebase the base commit.

Wait for PR of convert tool

**Comment by Duyi-Wang** [comment]
Add new features:
- Introduced prefix sharing feature.
- Introduce convert module to xfastertransformer python API.
- Auto-detect oneCCL environment in compilation. If not detected, oneCCL will be built from source.

**Review by changqi1 — APPROVED** [review]

**Pull request merged**
