### PR TITLE
[benchmark] Expose all parameters

### PR DESCRIPTION
**Pull request by JunxiChhen**
Got llama-2-7b result on HBM flat snc4:
./run_benchmark.sh -m llama-2-7b -d bf16_fp16 -bs 1 -b 1 -in 32 -out 32

==================================================llama-2-7b Final Performance==================================================
Inference Latency:      0.88 s
First token Avg Latency:        100.45 ms
Next token Max Latency: 25.24 ms
Next token Min Latency: 24.89 ms
Next token P90 Latency: 25.18 ms
Next token Avg Latency: 25.01 ms
Next token Latency:     25.18 ms

Which is on par with previews results.

### CODE REVIEW

**Comment by Duyi-Wang** [comment]
Add NF4 datatype in benchmark.

**Comment by JunxiChhen** [comment]
> Add NF4 datatype in benchmark.

Done

**Comment by Duyi-Wang** [comment]
https://github.com/intel/xFasterTransformer/blob/main/benchmark/benchmark.py#L74
Adjust relative path of `src`. The previous execution location was under 'benchmark/MODEL/', with the current location under 'benchmark/'. You can use the file location of 'benchmark.py' to determine the path.

**Comment by JunxiChhen** [comment]
> https://github.com/intel/xFasterTransformer/blob/main/benchmark/benchmark.py#L74 Adjust relative path of `src`. The previous execution location was under 'benchmark/MODEL/', with the current location under 'benchmark/'. You can use the file location of 'benchmark.py' to determine the path.

Done

**Review by Duyi-Wang — APPROVED** [review]

**Pull request merged**
