### PR TITLE
[3rdparty] remove oneCCL enviroment depency.

### PR DESCRIPTION
**Pull request by Duyi-Wang**

### CODE REVIEW

**Comment by Duyi-Wang** [comment]
@changqi1 Please help to update gitee.diff

**Comment by marvin-Yu** [comment]
link to issue #94

**Review by marvin-Yu — APPROVED** [review]

**Comment by changqi1** [comment]
@Duyi-Wang  There are 2 oneccl path? 
/3rdparty/oneCCL
/3rdparty/oneccl

**Comment by Duyi-Wang** [comment]
> @Duyi-Wang There are 2 oneccl path? /3rdparty/oneCCL /3rdparty/oneccl
Do you mean oneCCL in .gitignore?
Because currently, the manually installed directory is named "oneCCL," setting it as "oneccl" can avoid overwriting.

**Comment by Duyi-Wang** [comment]
Update README and prepare_oneccl.sh check path.

**Pull request merged**
